# -*- coding: utf-8 -*-
"""PRODIGY_GA_02_Image_Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pkyMBivBYQJI39W6_2Ryy9BAwL2qf5B
"""



!pip -q install diffusers transformers accelerate safetensors

!nvidia-smi

!pip -q install --upgrade diffusers transformers accelerate safetensors

import torch
from diffusers import StableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a magical fantasy castle floating in the sky, clouds, glowing lights, dreamy, ultra realistic, 4k"
image = pipe(prompt).images[0]
image

image.save("castle_dream.png")

import torch
from diffusers import StableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a magical fantasy castle floating in the sky, clouds, glowing lights, dreamy, ultra realistic, 4k"
image = pipe(prompt).images[0]
image.save("dream_castle.png")
image

image.save("dream castle.png")

image = pipe(prompt).images[0]
image